### ISSUE TITLE
HL bytecode hot reload and DomKit

### ISSUE THREAD

**Issue by rcstuber** [ncannasse/domkit#26]
Is it possible to use HL's bytecode hot reload functionality to reload changes to the SRC markup at runtime? 

I am currently able to do the reload and clear the children of a component and recreate it from the DomkitML, however it doesn't seem to pick up the actual changes made to the SRC variable, they stay the same. Is this even possible? How does Shiro test quick iterations on the markup?

Cheers

**Comment by ncannasse** [comment]
Hi ! HL bytecode hot reload is experimental and we haven't yet deployed it at Shiro. I need to look into it further to see if there's a specific problem wrt Domkit although it should be generic because SRC changes will trigger generation of initComponent() method. ATM at Shiro markup changes are tested by restarting the game.

**Comment by rcstuber** [comment]
Thanks for the insights! Reloading the markup through hot reload would be a massive speed up during development of UIs. Loading Markup from file (XML-like) during dev-time would also be a nice option, but maybe that's more difficult with inlining and such. I'll further look into it.
